/**
 * Irregular verbs for the "Động từ" tab. Based on the list of "Bảng 360 động từ bất quy tắc"
 * (thuvienphapluat.vn): its typos and odd entries are fixed (e.g. foreseen, the regular "work" is
 * left out), and very common verbs missing from it (do, have, hold, set, shut, bite…) are added.
 * Forms with two spellings are written "burnt/burned"; the first one is used to find the pattern.
 */
export interface IrregularVerb {
  base: string;
  past: string;
  participle: string;
  meaningVi: string;
  /** One of the ~100 verbs a learner meets first. */
  common: boolean;
  /** A short Vietnamese tip, e.g. how a form is pronounced. */
  noteVi?: string;
}

/** base, past, past participle, meaning. */
type Row = readonly [string, string, string, string];

const ROWS: readonly Row[] = [
  ['abide', 'abode/abided', 'abode/abided', 'tuân theo; chịu đựng'],
  ['arise', 'arose', 'arisen', 'phát sinh, nảy sinh'],
  ['awake', 'awoke', 'awoken', 'thức dậy; đánh thức'],
  ['be', 'was/were', 'been', 'thì, là, ở'],
  ['bear', 'bore', 'borne', 'mang; chịu đựng'],
  ['beat', 'beat', 'beaten', 'đánh; đánh bại'],
  ['become', 'became', 'become', 'trở nên, trở thành'],
  ['befall', 'befell', 'befallen', 'xảy đến'],
  ['begin', 'began', 'begun', 'bắt đầu'],
  ['behold', 'beheld', 'beheld', 'ngắm nhìn'],
  ['bend', 'bent', 'bent', 'bẻ cong; cúi xuống'],
  ['beset', 'beset', 'beset', 'bủa vây, bao quanh'],
  ['bespeak', 'bespoke', 'bespoken', 'chứng tỏ; đặt trước'],
  ['bet', 'bet', 'bet', 'đánh cược'],
  ['bid', 'bid', 'bid', 'trả giá'],
  ['bind', 'bound', 'bound', 'buộc, trói'],
  ['bite', 'bit', 'bitten', 'cắn'],
  ['bleed', 'bled', 'bled', 'chảy máu'],
  ['blow', 'blew', 'blown', 'thổi'],
  ['break', 'broke', 'broken', 'làm vỡ, đập vỡ'],
  ['breed', 'bred', 'bred', 'nuôi, gây giống'],
  ['bring', 'brought', 'brought', 'mang đến'],
  ['broadcast', 'broadcast', 'broadcast', 'phát sóng'],
  ['build', 'built', 'built', 'xây dựng'],
  ['burn', 'burnt/burned', 'burnt/burned', 'đốt, cháy'],
  ['burst', 'burst', 'burst', 'nổ tung, vỡ òa'],
  ['buy', 'bought', 'bought', 'mua'],
  ['cast', 'cast', 'cast', 'ném, tung; chọn vai'],
  ['catch', 'caught', 'caught', 'bắt, chụp'],
  ['chide', 'chid/chided', 'chidden/chided', 'mắng, quở trách'],
  ['choose', 'chose', 'chosen', 'chọn, lựa'],
  ['cleave', 'clove/cleft', 'cloven/cleft', 'chẻ, tách đôi'],
  ['cling', 'clung', 'clung', 'bám, níu lấy'],
  ['come', 'came', 'come', 'đến, đi đến'],
  ['cost', 'cost', 'cost', 'có giá là'],
  ['creep', 'crept', 'crept', 'bò, trườn'],
  ['crow', 'crew/crowed', 'crowed', '(gà) gáy'],
  ['cut', 'cut', 'cut', 'cắt, chặt'],
  ['deal', 'dealt', 'dealt', 'giao dịch; giải quyết'],
  ['dig', 'dug', 'dug', 'đào'],
  ['dive', 'dived/dove', 'dived', 'lặn, lao xuống'],
  ['do', 'did', 'done', 'làm'],
  ['draw', 'drew', 'drawn', 'vẽ; kéo'],
  ['dream', 'dreamt/dreamed', 'dreamt/dreamed', 'mơ, mơ thấy'],
  ['drink', 'drank', 'drunk', 'uống'],
  ['drive', 'drove', 'driven', 'lái xe'],
  ['dwell', 'dwelt/dwelled', 'dwelt/dwelled', 'cư ngụ, ở'],
  ['eat', 'ate', 'eaten', 'ăn'],
  ['fall', 'fell', 'fallen', 'ngã, rơi'],
  ['feed', 'fed', 'fed', 'cho ăn, nuôi'],
  ['feel', 'felt', 'felt', 'cảm thấy'],
  ['fight', 'fought', 'fought', 'chiến đấu, đánh nhau'],
  ['find', 'found', 'found', 'tìm thấy'],
  ['fit', 'fit/fitted', 'fit/fitted', 'vừa vặn'],
  ['flee', 'fled', 'fled', 'chạy trốn'],
  ['fling', 'flung', 'flung', 'ném mạnh, tung'],
  ['fly', 'flew', 'flown', 'bay'],
  ['forbear', 'forbore', 'forborne', 'nhịn, kiềm chế'],
  ['forbid', 'forbade', 'forbidden', 'cấm, ngăn cấm'],
  ['forecast', 'forecast/forecasted', 'forecast/forecasted', 'dự báo'],
  ['foresee', 'foresaw', 'foreseen', 'thấy trước'],
  ['foretell', 'foretold', 'foretold', 'đoán trước'],
  ['forget', 'forgot', 'forgotten', 'quên'],
  ['forgive', 'forgave', 'forgiven', 'tha thứ'],
  ['forsake', 'forsook', 'forsaken', 'từ bỏ, ruồng bỏ'],
  ['freeze', 'froze', 'frozen', 'đóng băng, làm đông'],
  ['get', 'got', 'got/gotten', 'có được, nhận được'],
  ['gild', 'gilded/gilt', 'gilded/gilt', 'mạ vàng'],
  ['gird', 'girded/girt', 'girded/girt', 'thắt, đeo vào'],
  ['give', 'gave', 'given', 'cho, đưa'],
  ['go', 'went', 'gone', 'đi'],
  ['grind', 'ground', 'ground', 'nghiền, xay'],
  ['grow', 'grew', 'grown', 'mọc, lớn lên; trồng'],
  ['hang', 'hung', 'hung', 'treo'],
  ['have', 'had', 'had', 'có'],
  ['hear', 'heard', 'heard', 'nghe'],
  ['heave', 'heaved/hove', 'heaved/hove', 'nâng lên, kéo lên'],
  ['hew', 'hewed', 'hewn/hewed', 'chặt, đẽo'],
  ['hide', 'hid', 'hidden', 'giấu, trốn'],
  ['hit', 'hit', 'hit', 'đánh, đụng'],
  ['hold', 'held', 'held', 'cầm, nắm; tổ chức'],
  ['hurt', 'hurt', 'hurt', 'làm đau, làm tổn thương'],
  ['inlay', 'inlaid', 'inlaid', 'cẩn, khảm'],
  ['input', 'input/inputted', 'input/inputted', 'nhập (dữ liệu)'],
  ['inset', 'inset', 'inset', 'dát, ghép vào'],
  ['keep', 'kept', 'kept', 'giữ'],
  ['kneel', 'knelt/kneeled', 'knelt/kneeled', 'quỳ'],
  ['knit', 'knit/knitted', 'knit/knitted', 'đan'],
  ['know', 'knew', 'known', 'biết, quen biết'],
  ['lay', 'laid', 'laid', 'đặt, để; đẻ (trứng)'],
  ['lead', 'led', 'led', 'dẫn dắt, lãnh đạo'],
  ['lean', 'leant/leaned', 'leant/leaned', 'dựa, tựa'],
  ['leap', 'leapt/leaped', 'leapt/leaped', 'nhảy vọt'],
  ['learn', 'learnt/learned', 'learnt/learned', 'học'],
  ['leave', 'left', 'left', 'rời đi; để lại'],
  ['lend', 'lent', 'lent', 'cho mượn'],
  ['let', 'let', 'let', 'để cho, cho phép'],
  ['lie', 'lay', 'lain', 'nằm'],
  ['light', 'lit/lighted', 'lit/lighted', 'thắp sáng, châm lửa'],
  ['lose', 'lost', 'lost', 'làm mất; thua'],
  ['make', 'made', 'made', 'làm, chế tạo'],
  ['mean', 'meant', 'meant', 'có nghĩa là; định'],
  ['meet', 'met', 'met', 'gặp'],
  ['mislay', 'mislaid', 'mislaid', 'để thất lạc'],
  ['mislead', 'misled', 'misled', 'làm lạc hướng, đánh lừa'],
  ['misread', 'misread', 'misread', 'đọc sai, hiểu sai'],
  ['misspell', 'misspelt/misspelled', 'misspelt/misspelled', 'viết sai chính tả'],
  ['mistake', 'mistook', 'mistaken', 'nhầm lẫn'],
  ['misunderstand', 'misunderstood', 'misunderstood', 'hiểu lầm'],
  ['mow', 'mowed', 'mown/mowed', 'cắt cỏ'],
  ['outbid', 'outbid', 'outbid', 'trả giá cao hơn'],
  ['outdo', 'outdid', 'outdone', 'làm giỏi hơn'],
  ['outgrow', 'outgrew', 'outgrown', 'lớn nhanh hơn; lớn quá khổ'],
  ['output', 'output/outputted', 'output/outputted', 'xuất (dữ liệu)'],
  ['outrun', 'outran', 'outrun', 'chạy nhanh hơn'],
  ['outsell', 'outsold', 'outsold', 'bán chạy hơn'],
  ['overcome', 'overcame', 'overcome', 'vượt qua, khắc phục'],
  ['overdo', 'overdid', 'overdone', 'làm quá mức'],
  ['overeat', 'overate', 'overeaten', 'ăn quá nhiều'],
  ['overfly', 'overflew', 'overflown', 'bay qua'],
  ['overhang', 'overhung', 'overhung', 'nhô ra phía trên'],
  ['overhear', 'overheard', 'overheard', 'nghe lỏm'],
  ['overlay', 'overlaid', 'overlaid', 'phủ lên'],
  ['overpay', 'overpaid', 'overpaid', 'trả quá nhiều tiền'],
  ['overrun', 'overran', 'overrun', 'tràn ngập'],
  ['oversee', 'oversaw', 'overseen', 'giám sát'],
  ['overshoot', 'overshot', 'overshot', 'vượt quá (mục tiêu)'],
  ['oversleep', 'overslept', 'overslept', 'ngủ quên'],
  ['overtake', 'overtook', 'overtaken', 'vượt qua, đuổi kịp'],
  ['overthrow', 'overthrew', 'overthrown', 'lật đổ'],
  ['pay', 'paid', 'paid', 'trả (tiền)'],
  ['prove', 'proved', 'proven/proved', 'chứng minh'],
  ['put', 'put', 'put', 'đặt, để'],
  ['quit', 'quit', 'quit', 'bỏ, thôi'],
  ['read', 'read', 'read', 'đọc'],
  ['rebuild', 'rebuilt', 'rebuilt', 'xây lại'],
  ['redo', 'redid', 'redone', 'làm lại'],
  ['remake', 'remade', 'remade', 'làm lại'],
  ['rend', 'rent', 'rent', 'xé toạc'],
  ['repay', 'repaid', 'repaid', 'trả lại (tiền)'],
  ['resell', 'resold', 'resold', 'bán lại'],
  ['retell', 'retold', 'retold', 'kể lại'],
  ['rewrite', 'rewrote', 'rewritten', 'viết lại'],
  ['rid', 'rid', 'rid', 'loại bỏ, giải thoát'],
  ['ride', 'rode', 'ridden', 'cưỡi, đi (xe đạp, ngựa)'],
  ['ring', 'rang', 'rung', 'rung (chuông); gọi điện'],
  ['rise', 'rose', 'risen', 'mọc; tăng lên'],
  ['run', 'ran', 'run', 'chạy'],
  ['saw', 'sawed', 'sawn/sawed', 'cưa'],
  ['say', 'said', 'said', 'nói'],
  ['see', 'saw', 'seen', 'nhìn thấy'],
  ['seek', 'sought', 'sought', 'tìm kiếm'],
  ['sell', 'sold', 'sold', 'bán'],
  ['send', 'sent', 'sent', 'gửi'],
  ['set', 'set', 'set', 'đặt; thiết lập'],
  ['sew', 'sewed', 'sewn/sewed', 'may, khâu'],
  ['shake', 'shook', 'shaken', 'lắc, rung'],
  ['shed', 'shed', 'shed', 'làm rơi, rụng'],
  ['shine', 'shone', 'shone', 'chiếu sáng'],
  ['shoot', 'shot', 'shot', 'bắn'],
  ['show', 'showed', 'shown/showed', 'cho xem, chỉ'],
  ['shrink', 'shrank', 'shrunk', 'co lại'],
  ['shut', 'shut', 'shut', 'đóng lại'],
  ['sing', 'sang', 'sung', 'hát'],
  ['sink', 'sank', 'sunk', 'chìm'],
  ['sit', 'sat', 'sat', 'ngồi'],
  ['slay', 'slew', 'slain', 'giết'],
  ['sleep', 'slept', 'slept', 'ngủ'],
  ['slide', 'slid', 'slid', 'trượt'],
  ['sling', 'slung', 'slung', 'quăng, ném'],
  ['slink', 'slunk', 'slunk', 'lẻn đi'],
  ['slit', 'slit', 'slit', 'rạch, khứa'],
  ['smell', 'smelt/smelled', 'smelt/smelled', 'ngửi; có mùi'],
  ['smite', 'smote', 'smitten', 'đập mạnh'],
  ['sow', 'sowed', 'sown/sowed', 'gieo (hạt)'],
  ['speak', 'spoke', 'spoken', 'nói'],
  ['speed', 'sped/speeded', 'sped/speeded', 'tăng tốc, chạy nhanh'],
  ['spell', 'spelt/spelled', 'spelt/spelled', 'đánh vần'],
  ['spend', 'spent', 'spent', 'tiêu (tiền); dành (thời gian)'],
  ['spill', 'spilt/spilled', 'spilt/spilled', 'làm đổ, tràn ra'],
  ['spin', 'spun', 'spun', 'quay, xoay'],
  ['spit', 'spat/spit', 'spat/spit', 'nhổ, khạc'],
  ['split', 'split', 'split', 'tách ra, chia'],
  ['spoil', 'spoilt/spoiled', 'spoilt/spoiled', 'làm hỏng; chiều hư'],
  ['spread', 'spread', 'spread', 'lan truyền; trải ra'],
  ['spring', 'sprang', 'sprung', 'nhảy, bật lên'],
  ['stand', 'stood', 'stood', 'đứng'],
  ['steal', 'stole', 'stolen', 'ăn trộm'],
  ['stick', 'stuck', 'stuck', 'dán, dính'],
  ['sting', 'stung', 'stung', 'châm, chích'],
  ['stink', 'stank/stunk', 'stunk', 'bốc mùi hôi'],
  ['strew', 'strewed', 'strewn/strewed', 'rải, rắc'],
  ['stride', 'strode', 'stridden', 'sải bước'],
  ['strike', 'struck', 'struck', 'đánh, đập; đình công'],
  ['string', 'strung', 'strung', 'xâu, buộc dây'],
  ['strive', 'strove', 'striven', 'cố gắng'],
  ['swear', 'swore', 'sworn', 'thề; chửi thề'],
  ['sweep', 'swept', 'swept', 'quét'],
  ['swell', 'swelled', 'swollen/swelled', 'phồng lên, sưng'],
  ['swim', 'swam', 'swum', 'bơi'],
  ['swing', 'swung', 'swung', 'đung đưa'],
  ['take', 'took', 'taken', 'cầm, lấy'],
  ['teach', 'taught', 'taught', 'dạy'],
  ['tear', 'tore', 'torn', 'xé, làm rách'],
  ['tell', 'told', 'told', 'kể, bảo'],
  ['think', 'thought', 'thought', 'nghĩ'],
  ['throw', 'threw', 'thrown', 'ném'],
  ['thrust', 'thrust', 'thrust', 'đẩy mạnh, đâm'],
  ['tread', 'trod', 'trodden/trod', 'giẫm, đạp'],
  ['unbend', 'unbent', 'unbent', 'làm thẳng lại; thư giãn'],
  ['undercut', 'undercut', 'undercut', 'bán rẻ hơn'],
  ['undergo', 'underwent', 'undergone', 'trải qua'],
  ['underlie', 'underlay', 'underlain', 'làm nền tảng cho'],
  ['underpay', 'underpaid', 'underpaid', 'trả lương thấp'],
  ['undersell', 'undersold', 'undersold', 'bán rẻ hơn'],
  ['understand', 'understood', 'understood', 'hiểu'],
  ['undertake', 'undertook', 'undertaken', 'đảm nhận'],
  ['underwrite', 'underwrote', 'underwritten', 'bảo lãnh, bảo hiểm'],
  ['undo', 'undid', 'undone', 'tháo ra; hủy bỏ'],
  ['unfreeze', 'unfroze', 'unfrozen', 'làm tan băng'],
  ['unwind', 'unwound', 'unwound', 'tháo ra; thư giãn'],
  ['uphold', 'upheld', 'upheld', 'ủng hộ, giữ vững'],
  ['upset', 'upset', 'upset', 'làm buồn lòng; làm đổ'],
  ['wake', 'woke', 'woken', 'thức dậy; đánh thức'],
  ['waylay', 'waylaid', 'waylaid', 'mai phục, chặn đường'],
  ['wear', 'wore', 'worn', 'mặc, đội, đeo'],
  ['weave', 'wove', 'woven', 'dệt'],
  ['wed', 'wed/wedded', 'wed/wedded', 'kết hôn'],
  ['weep', 'wept', 'wept', 'khóc'],
  ['wet', 'wet/wetted', 'wet/wetted', 'làm ướt'],
  ['win', 'won', 'won', 'thắng'],
  ['wind', 'wound', 'wound', 'quấn; lên dây (đồng hồ)'],
  ['withdraw', 'withdrew', 'withdrawn', 'rút lui; rút (tiền)'],
  ['withhold', 'withheld', 'withheld', 'giữ lại, từ chối'],
  ['withstand', 'withstood', 'withstood', 'chịu đựng, chống lại'],
  ['wring', 'wrung', 'wrung', 'vắt, vặn'],
  ['write', 'wrote', 'written', 'viết'],
];

/** The verbs learners meet first (A1–B1), shown by the "Thông dụng" filter. */
const COMMON = new Set([
  'be', 'beat', 'become', 'begin', 'bend', 'bet', 'bite', 'blow', 'break', 'bring', 'build', 'burn',
  'buy', 'catch', 'choose', 'come', 'cost', 'cut', 'deal', 'dig', 'do', 'draw', 'dream', 'drink',
  'drive', 'eat', 'fall', 'feed', 'feel', 'fight', 'find', 'fly', 'forget', 'forgive', 'freeze', 'get',
  'give', 'go', 'grow', 'hang', 'have', 'hear', 'hide', 'hit', 'hold', 'hurt', 'keep', 'know', 'lay',
  'lead', 'learn', 'leave', 'lend', 'let', 'lie', 'light', 'lose', 'make', 'mean', 'meet', 'pay', 'put',
  'quit', 'read', 'ride', 'ring', 'rise', 'run', 'say', 'see', 'sell', 'send', 'set', 'shake', 'shine',
  'shoot', 'show', 'shut', 'sing', 'sink', 'sit', 'sleep', 'smell', 'speak', 'spell', 'spend', 'spread',
  'stand', 'steal', 'stick', 'swim', 'swing', 'take', 'teach', 'tear', 'tell', 'think', 'throw',
  'understand', 'upset', 'wake', 'wear', 'win', 'write',
]);

/** Tips for the forms learners often get wrong. */
const NOTES: Record<string, string> = {
  read: 'Viết giống nhau nhưng V2, V3 đọc là /red/ (V1 đọc là /riːd/).',
  lie: 'Nghĩa "nói dối" là động từ có quy tắc: lie – lied – lied.',
  lay: 'Đừng nhầm với lie (nằm): lie – lay – lain.',
  hang: 'Nghĩa "treo cổ" là động từ có quy tắc: hang – hanged – hanged.',
  be: 'V2: was dùng với I, he, she, it; were dùng với you, we, they.',
  get: 'gotten dùng trong tiếng Anh – Mỹ, got dùng trong tiếng Anh – Anh.',
  wind: 'Đọc /waɪnd/; danh từ wind (gió) đọc /wɪnd/.',
  learn: 'learnt dùng nhiều trong tiếng Anh – Anh, learned trong tiếng Anh – Mỹ.',
};

export const IRREGULAR_VERBS: readonly IrregularVerb[] = ROWS.map(([base, past, participle, meaningVi]) => ({
  base,
  past,
  participle,
  meaningVi,
  common: COMMON.has(base),
  ...(NOTES[base] ? { noteVi: NOTES[base] } : {}),
}));
